### ISSUE TITLE
not pulling value into JS

### ISSUE THREAD

**Issue by OptikWebCreative** [NeonTigerWeb/onWebChat#1]
JS in partial not pulling the chatid value into the script causing the script to fail.

Hardcoding the value enables the script to work.

**Comment by OptikWebCreative** [comment]
faulty file path /templates/partials/onwebchat.html.twig

**Comment by OptikWebCreative** [comment]
SOLVED

**Comment by OleVik** [comment]
I added a PR for a global config: #2 .
